// Run with NODE_PATH pointing at Playwright. Uses an isolated browser and local test server.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
 const server=http.createServer((req,res)=>{const file=req.url==='/'?'index.html':req.url.slice(1);if(!['index.html','amazon-prep.js','amazon-prep-data.js','amazon-prep.css','favicon.svg'].includes(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(path.join(__dirname,'..',file)));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true, channel:process.env.PLAYWRIGHT_CHANNEL || "chrome"});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.stack));
 await page.route('**/*supabase*',route=>route.abort());
 await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(()=>{state.todos=Array.from({length:90},(_,i)=>({id:'day-'+i,title:'Task '+i,date:dateKey(new Date(2026,6,1+i)),priority:'medium',done:false}));state.todos.push({id:'hidden-completed',title:'Completed task',date:state.todos[0].date,priority:'low',done:true});save();switchTab('todo');});
 await page.getByRole('button',{name:'Collapse all · bottom right ↘'}).click();
 await page.waitForTimeout(300);
 assert.equal(await page.locator('.todo-date-card.date-only').count(),90);
 assert.equal(await page.locator('.todo-items:visible').count(),0);
 assert.equal(await page.locator('.todo-card-count:visible,.todo-calendar:visible').count(),0);
 assert.equal(await page.evaluate(()=>{const b=document.getElementById('todoDateGrid');return Math.abs(b.scrollHeight-b.clientHeight-b.scrollTop)<2 && Math.abs(b.scrollWidth-b.clientWidth-b.scrollLeft)<2;}),true);
 await page.locator('.todo-date-only').last().click();
 assert.equal(await page.locator('.todo-items:visible').count(),1);
 await page.locator('.todo-expand').last().click();
 assert.equal(await page.locator('.todo-items:visible').count(),0);
 await page.getByRole('button',{name:'Delete cards',exact:true}).click();
 await page.locator('.select-todo-card').first().check();
 await page.locator('.select-todo-card').nth(1).check();
 page.once('dialog',dialog=>dialog.dismiss());
 await page.getByRole('button',{name:'Delete selected (2)',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.todos.length),91);
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Delete selected (2)',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.todos.length),88);
 await page.reload();
 assert.equal(await page.locator('.todo-date-card').count(),88);
 assert.equal(await page.evaluate(()=>state.todos.some(t=>t.id==='hidden-completed')),false);
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Collapse all · bottom right ↘'}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('PASS: date-only collapse, independent expansion, bottom-right scroll, bulk selection, cancel/confirm deletion, reload persistence, mobile');
 await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1);});
